export const MOVIES = [
  {
    id: 0,
    title: 'After',
    description: 'Some description movie AFTER',
    daySchedule: ['mo', 'tu', 'we'],
    timeSchedule: ['11:00', '13:00', '15:00', '20:00'],
    imgUrl: '../../assets/img/movies/movie_after.jpg',
  },
  {
    id: 1,
    title: 'Alien Invation',
    description: 'Some description movie Alien Invation',
    daySchedule: ['mo', 'tu', 'we'],
    timeSchedule: ['11:00', '13:00', '15:00', '20:00'],
    imgUrl: '../../assets/img/movies/movie_alien_invasion.jpg',
  },
  {
    id: 2,
    title: 'Astro Traveller',
    description: 'Some description movie Astro Travelle',
    daySchedule: ['mo', 'tu', 'we'],
    timeSchedule: ['11:00', '13:00', '15:00', '20:00'],
    imgUrl: '../../assets/img/movies/movie_astro_traveller.jpg',
  },
  {
    id: 3,
    title: 'Broken Mirrors',
    description: 'Some description movie Broken Mirrors',
    daySchedule: ['mo', 'tu', 'we'],
    timeSchedule: ['11:00', '13:00', '15:00', '20:00'],
    imgUrl: '../../assets/img/movies/movie_broken_mirrors.jpg',
  },
  {
    id: 4,
    title: 'Dark Secret',
    description: 'Some description movie Dark Secret',
    daySchedule: ['mo', 'tu', 'we'],
    timeSchedule: ['11:00', '13:00', '15:00', '20:00'],
    imgUrl: '../../assets/img/movies/movie_dark_secret.jpg',
  },
  {
    id: 5,
    title: 'Darkness',
    description: 'Some description movie Darkness',
    daySchedule: ['mo', 'tu', 'we'],
    timeSchedule: ['11:00', '13:00', '15:00', '20:00'],
    imgUrl: '../../assets/img/movies/movie_darkness.jpg',
  },
  {
    id: 6,
    title: 'Demens',
    description: 'Some description movie Demens',
    daySchedule: ['mo', 'tu', 'we'],
    timeSchedule: ['11:00', '13:00', '15:00', '20:00'],
    imgUrl: '../../assets/img/movies/movie_demens.jpg',
  },
  {
    id: 7,
    title: 'Distance Heart',
    description: 'Some description movie Distance Heart',
    daySchedule: ['mo', 'tu', 'we'],
    timeSchedule: ['11:00', '13:00', '15:00', '20:00'],
    imgUrl: '../../assets/img/movies/movie_distance_heart.jpg',
  },
  {
    id: 8,
    title: 'Dreams',
    description: 'Some description movie Dreams',
    daySchedule: ['mo', 'tu', 'we'],
    timeSchedule: ['11:00', '13:00', '15:00', '20:00'],
    imgUrl: '../../assets/img/movies/movie_dreams.jpg',
  },
  {
    id: 9,
    title: 'Freedom',
    description: 'Some description movie Freedom',
    daySchedule: ['mo', 'tu', 'we'],
    timeSchedule: ['11:00', '13:00', '15:00', '20:00'],
    imgUrl: '../../assets/img/movies/movie_freedom.jpg',
  },
  {
    id: 10,
    title: 'The Jungle Beast',
    description: 'Some description movie The Jungle Beast',
    daySchedule: ['mo', 'tu', 'we'],
    timeSchedule: ['11:00', '13:00', '15:00', '20:00'],
    imgUrl: '../../assets/img/movies/movie_jungle_beast.jpg',
  },
  {
    id: 11,
    title: 'War Lords',
    description: 'Some description movie War Lords',
    daySchedule: ['mo', 'tu', 'we'],
    timeSchedule: ['11:00', '13:00', '15:00', '20:00'],
    imgUrl: '../../assets/img/movies/movie_war_lords.jpg',
  },
];
